//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Service.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrabalhoDADEntities : DbContext
    {
        public TrabalhoDADEntities()
            : base("name=TrabalhoDADEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categoria> categoria { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<compra> compra { get; set; }
        public virtual DbSet<fornecedor> fornecedor { get; set; }
        public virtual DbSet<itenscompra> itenscompra { get; set; }
        public virtual DbSet<itensvenda> itensvenda { get; set; }
        public virtual DbSet<parcelascompra> parcelascompra { get; set; }
        public virtual DbSet<parcelasvenda> parcelasvenda { get; set; }
        public virtual DbSet<produto> produto { get; set; }
        public virtual DbSet<subcategoria> subcategoria { get; set; }
        public virtual DbSet<tipopagamento> tipopagamento { get; set; }
        public virtual DbSet<undmedida> undmedida { get; set; }
        public virtual DbSet<venda> venda { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    }
}
