//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class itenscompra
    {
        public int itc_cod { get; set; }
        public Nullable<double> itc_qtde { get; set; }
        public Nullable<decimal> itc_valor { get; set; }
        public int com_cod { get; set; }
        public int pro_cod { get; set; }
    
        public virtual compra compra { get; set; }
        public virtual produto produto { get; set; }
    }
}
