//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class itensvenda
    {
        public int itv_cod { get; set; }
        public Nullable<double> itv_qtde { get; set; }
        public Nullable<decimal> itv_valor { get; set; }
        public int ven_cod { get; set; }
        public int pro_cod { get; set; }
    
        public virtual venda venda { get; set; }
        public virtual produto produto { get; set; }
    }
}
