//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class parcelascompra
    {
        public int pco_cod { get; set; }
        public Nullable<decimal> pco_valor { get; set; }
        public Nullable<System.DateTime> pco_datapagto { get; set; }
        public Nullable<System.DateTime> pco_datavecto { get; set; }
        public int com_cod { get; set; }
    
        public virtual compra compra { get; set; }
    }
}
