//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class produto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public produto()
        {
            this.itenscompra = new HashSet<itenscompra>();
            this.itensvenda = new HashSet<itensvenda>();
        }
    
        public int pro_cod { get; set; }
        public string pro_nome { get; set; }
        public string pro_descricao { get; set; }
        public byte[] pro_foto { get; set; }
        public Nullable<decimal> pro_valorpago { get; set; }
        public Nullable<decimal> pro_valorvenda { get; set; }
        public Nullable<double> pro_qtde { get; set; }
        public Nullable<int> umed_cod { get; set; }
        public Nullable<int> cat_cod { get; set; }
        public Nullable<int> scat_cod { get; set; }
    
        public virtual categoria categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<itenscompra> itenscompra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<itensvenda> itensvenda { get; set; }
        public virtual subcategoria subcategoria { get; set; }
        public virtual undmedida undmedida { get; set; }
    }
}
